# Generated by Django 4.1.13 on 2024-04-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidscoin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reel',
        ),
    ]
