# Generated by Django 4.1.13 on 2024-04-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidscoin', '0002_delete_reel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
