# Generated by Django 4.1.13 on 2024-04-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidscoin', '0005_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Reelid',
        ),
    ]
