# Generated by Django 4.1.13 on 2024-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidscoin', '0008_reels_delete_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='_id',
            field=models.CharField(default='662806b0c8569ab3f478eabe', max_length=50),
        ),
    ]
